'use client';
import ReactMarkdown from 'react-markdown';
import { useState } from 'react';
import Link from 'next/link';

const markdownContent = `
# DeepThought Labs Web Presence: The "Transparent Workshop" Strategy

This document outlines the strategic, phased development of the DeepThought Labs web presence, evolving it from a conventional marketing site into an authentic, public-facing extension of our core product's philosophy. Our web presence is a "Transparent Workshop"—a space for honesty, transparency, and utility, built on a deep respect for the user's intelligence and sovereignty.

## Guiding Principles:

*   **App-Centric, Not Web-Centric:** The DeepThought application is the center of the user's universe. The website is a utility, not a destination.
*   **Distributed Knowledge, Not Centralized:** The ultimate goal is a peer-to-peer network of knowledge shared directly between DeepThought instances, not a central web portal.
*   **Authentic Demonstration, Not Predatory Marketing:** The site's purpose is to provide undeniable proof of our technology's value, allowing users to protect themselves from "AI slop" and empower them to charge 10x in consulting fees.
*   **Community Access: Product-Led Authentication:** No mandatory login or email harvesting for community features. Access will be granted via a key generated by the owned DeepThought desktop application, ensuring anonymous-but-verified access.
*   **Business Model: Content is Free, Context is Billable:** All thought leadership and documentation are public and free. Our paid service is high-touch consulting, helping clients apply complex ideas to their specific problems.
*   **License Portability: User Ownership Protection:** The secure utility page is for protecting the user's ownership, allowing them to retrieve their license key and download their entitled app version, ensuring their "intellectual fortress" moves with them.

---

### Phase 1: The Atelier & Foundational Texts

**Goal:** To establish a single, high-value public touchpoint that is 100% authentic to our philosophy and technology.

*   **1.1. Build "The Atelier: The Workbench for Agentic AI"**
    *   **Why:** This is the centerpiece of our web presence and the "money shot." It provides honest, interactive proof of our "Architecture of Synthesis." It allows users to experience our technology firsthand.
    *   **Key Deliverables:**
        *   A lightweight, interactive demo of the GenUI framework directly on the website.
        *   A simple input for users to provide a textual prompt (e.g., "a user profile card with an avatar and a follow button").
        *   Real-time generation and display of a UI mock-up based on the prompt.
    *   **Success Metrics:** Functional interactive demo, positive user feedback on the "wow" factor and utility.
    *   **Technologies:** Next.js (for dynamic server-side capabilities), React (for UI), Cloudflare Workers/AI (for prompt processing and UI generation).
    *   **Dependencies:** Core GenUI logic (from DeepThought codebase) accessible via API.

*   **1.2. Publish the Canon**
    *   **Why:** To provide the intellectual foundation for what users experience in The Atelier and establish DeepThought Labs as a thought leader. All content is public and free.
    *   **Key Deliverables:**
        *   High-quality, standalone web pages for core philosophical and architectural white papers (e.g., "The Architecture of Synthesis," "The Principle of Symbiotic Disbelief," "The Emergent Application").
        *   Integration of \\\`Architecture_of_Synthesis.md\\\` as the first published canon.
    *   **Success Metrics:** Whitepapers are accessible, well-formatted, and clearly convey our core ideas.
    *   **Technologies:** Next.js (for static content generation), \\\`react-markdown\\\`, Tailwind CSS (\\\`@tailwindcss/typography\\\`).
    *   **Dependencies:** Curated content from \\\`deepthoughtdocs\\\` repository.

---

### Phase 2: The Sovereign User's Toolkit & Open Blueprint

**Goal:** To provide essential utilities for our users and the transparent "look under the hood" that our philosophy demands.

*   **2.1. Deploy the Sovereign Utility Page**
    *   **Why:** To provide a secure, simple mechanism for license holders to manage their ownership, ensuring license portability and protecting user data. This is a tool, not a gate.
    *   **Key Deliverables:**
        *   A secure web page for license holders to retrieve their purchased key.
        *   Direct download access to specific, versioned DeepThought desktop applications they are entitled to.
    *   **Success Metrics:** Users can securely access their license information and downloads.
    *   **Technologies:** Next.js (for secure server-side rendering and API routes), secure authentication/authorization mechanisms (to be defined, potentially tied to license key validation).
    *   **Dependencies:** License management system (backend).

*   **2.2. Establish the Open Blueprint**
    *   **Why:** To share hard-won knowledge and demonstrate deep, API-less integrations, fostering a community of empowered users. This is where inference over instruction is demonstrated.
    *   **Key Deliverables:**
        *   A public-facing section of the site dedicated to sharing high-value "playbooks" and examples.
        *   Content demonstrating deep integrations with local-first tools (e.g., Logseq, LibreOffice).
        *   "Vanguard Partner Journals" – authentic stories of how partners solve problems, generated by AI and presented as-is.
    *   **Success Metrics:** Playbooks are clear, actionable, and demonstrate the power of DeepThought's integration capabilities.
    *   **Technologies:** Next.js, \\\`react-markdown\\\`, potentially code syntax highlighting libraries.
    *   **Dependencies:** Curated content from \\\`deepthoughtdocs\\\` repository, AI tools for generating partner journals.

---

### Phase 3: The Distributed Knowledge Network (V2 Vision)

**Goal:** To transcend the website and create a living, peer-to-peer ecosystem for sharing knowledge directly between DeepThought instances. This is the ultimate vision for our community.

*   **3.1. Implement Product-Led Authentication**
    *   **Why:** To enable anonymous-but-verified access to community features, respecting user privacy while protecting the network.
    *   **Key Deliverables:**
        *   Mechanism within the DeepThought desktop app to generate a unique, anonymous key for web/community access.
        *   Backend service to validate these keys for community features.
    *   **Success Metrics:** Secure, privacy-preserving user authentication for community features.
    *   **Technologies:** DeepThought desktop app integration, secure backend services.
    *   **Dependencies:** DeepThought desktop app development.

*   **3.2. Build the Community Innovation Sync**
    *   **Why:** To allow users to make their local DeepThought instance as smart as anyone else's by syncing a shared "Community Innovation" graph, fostering collaborative knowledge sharing.
    *   **Key Deliverables:**
        *   Backend service for managing and distributing a shared "Community Innovation" graph (blocks, personas, workflows).
        *   Integration within the DeepThought desktop app to opt-in and sync this graph.
    *   **Success Metrics:** Users can seamlessly share and receive knowledge nuggets within their DeepThought instances.
    *   **Technologies:** Distributed database technologies, peer-to-peer networking concepts, DeepThought desktop app integration.
    *   **Dependencies:** DeepThought desktop app development, backend infrastructure for distributed sync.

---

### Technical Setup & Conventions for Contributors

This section provides essential information for any developer contributing to the \\\`deepthought_labs_web\\\` project.

*   **Repository Access:**
    *   Clone the repository: \\\`git clone https://github.com/EpistemonLex/deepthought_labs_web.git\\\`
    *   Ensure your GitHub CLI is authenticated (\\\`gh auth status\\\`).
*   **Local Development Environment:**
    *   **Node.js:** Use \\\`nvm\\\` (Node Version Manager) to manage Node.js versions. Recommended version: \\\`v20.x\\\` (LTS).
    *   **Package Manager:** \\\`npm\\\` (Node Package Manager).
    *   **Install Dependencies:** Navigate to the project root and run \\\`npm install\\\`.
    *   **Start Development Server:** \\\`npm run dev\\\` (runs on \\\`localhost:3000\\\` by default, but we are currently using \\\`localhost:3001\\\` to avoid conflicts with Gitea).
    *   **Access:** Open your browser to \\\`http://localhost:3001\\\`.
*   **Code Quality & Style:**
    *   **Linter:** ESLint is configured. Run \\\`npm run lint\\\` to check for code style and potential errors.
    *   **Formatting:** Prettier is integrated via ESLint.
*   **File Structure Conventions:**
    *   \\\`src/app/\\\`: Next.js App Router pages and layouts.
    *   \\\`src/components/\\\`: Reusable React components.
    *   \\\`src/styles/\\\`: Global CSS.
    *   \\\`docs/\\\`: Project documentation, including original markdown files (\\\`Architecture_of_Synthesis.md\\\`, \\\`web_roadmap.md\\\`, \\\`daily_handoff_*.md\\\`).
*   **Deployment Process:**
    *   The \\\`deepthought_labs_web\\\` repository is connected to Cloudflare Pages.
    *   Pushing changes to the \\\`main\\\` branch automatically triggers a new deployment.

---

### Current Status (as of 2025-09-19)

*   **Project Initialized:** Next.js project with TypeScript, Tailwind CSS, and ESLint is set up.
*   **GitHub Integration:** Repository created, initial project files committed and pushed.
*   **Development Server:** Running on \\\`http://localhost:3001\\\`.
*   **Landing Page:** Basic structure in \\\`src/app/page.tsx\\\` with header, hero, and narrative section placeholders. Content for "Problem," "Solution," and "Proof" sections refined for conciseness.
*   **Whitepaper:** \\\`Architecture_of_Synthesis.md\\\` integrated into \\\`src/app/whitepaper/page.tsx\\\` using \\\`react-markdown\\\` and styled with \\\`@tailwindcss/typography\\\`.
*   **Roadmap Page:** \\\`src/app/roadmap/page.tsx\\\` populated with the enhanced "Transparent Workshop" strategy.
*   **Navigation:** Links to \\\`/whitepaper\\\`, \\\`/roadmap\\\`, and \\\`/atelier\\\` added to the main site header.
*   **The Atelier (GenUI Demo):** \\\`src/app/atelier/page.tsx\\\` created with basic UI (input, display area) and a placeholder API route (\\\`src/app/api/genui/route.ts\\\`) for mock responses.
*   **Daily Handoff:** This report (\\\`docs/daily_handoff_2025-09-19.md\\\`) has been created.

### Immediate Next Actions:

1.  **Populate Roadmap Page:** Update \\\`src/app/roadmap/page.tsx\\\` with this enhanced "Transparent Workshop" strategy.
2.  **Integrate Roadmap into Navigation:** Add a link to \\\`/roadmap\\\` in the site's header.
3.  **Populate Landing Page Sections:** Begin filling in the "Problem," "Solution," and "Proof" sections on \\\`src/app/page.tsx\\\` with content derived from the \\\`Architecture_of_Synthesis.md\\\` and the overall vision.

---
`;

export default function Roadmap() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  return (
    <div className="bg-gray-900 text-white min-h-screen">
      <header className="container mx-auto px-6 py-4 flex justify-between items-center border-b border-gray-700 pb-4">
        <h1 className="text-2xl font-bold">DeepThought Labs</h1>
        <div className="md:hidden">
          <button
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            className="text-gray-300 hover:text-white focus:outline-none"
          >
            <svg
              className="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4 6h16M4 12h16M4 18h16"
              ></path>
            </svg>
          </button>
        </div>
        <nav className="hidden md:flex space-x-4">
          <Link
            href="/whitepaper"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            Whitepaper
          </Link>
          <Link
            href="/ukw-framework"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            UKW Framework
          </Link>
          <Link
            href="/conceptual-seeding"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            Conceptual Seeding
          </Link>
          <Link
            href="/symbiotic-disbelief"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            Symbiotic Disbelief
          </Link>
          <Link
            href="/emergent-application"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            Emergent Application
          </Link>
          <Link
            href="/roadmap"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            Roadmap
          </Link>
          <Link
            href="/atelier"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            The Atelier
          </Link>
          <Link
            href="/#contact"
            className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
          >
            Contact
          </Link>
        </nav>
        {isMenuOpen && (
          <div className="md:hidden absolute top-16 left-0 w-full bg-gray-900 border-b border-gray-700 py-4 z-10">
            <nav className="flex flex-col items-center space-y-2">
              <Link
                href="/whitepaper"
                className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-base font-medium"
              >
                Whitepaper
              </Link>
              <Link
                href="/ukw-framework"
                className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-base font-medium"
              >
                UKW Framework
              </Link>
              <Link
                href="/roadmap"
                className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-base font-medium"
              >
                Roadmap
              </Link>
              <Link
                href="/atelier"
                className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-base font-medium"
              >
                The Atelier
              </Link>
              <Link
                href="/#contact"
                className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-base font-medium"
              >
                Contact
              </Link>
            </nav>
          </div>
        )}
      </header>
      <main className="container mx-auto px-6 py-20">
        <article className="prose prose-invert lg:prose-xl mx-auto">
          <ReactMarkdown>{markdownContent}</ReactMarkdown>
        </article>
      </main>
      <footer className="bg-gray-900 py-10 border-t border-gray-700">
        <div className="container mx-auto px-6 text-center">
          <p className="text-gray-400">
            &copy; {new Date().getFullYear()} DeepThought Labs. All rights
            reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
